name             'sprout-osx-android'
maintainer       'Pivotal Labs'
maintainer_email 'accounts@pivotallabs.com'
license          'MIT'
description      'Installs and configures a workstation for Android development'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.1'
supports         'mac_os_x'
depends          'sprout-osx-base'
depends          'dmg'
